GET http://localhost:9000/users

### QUESTIONS ROUTE

GET http://localhost:9000/questions

###

GET http://localhost:9000/questions/1

###

POST http://localhost:9000/questions/1
Content-Type: application/json

{
    "user_id" : 2,
    "question_text" : "What is the single most influential book every designer programmer should read ?"
}

###

###

PUT http://localhost:9000/questions/5
Content-Type: application/json

{
    "user_id" : 2,
    "question_text" : "Attention au transit avec la pizza méxicaine"
}

###

POST http://localhost:9000/users
Content-type: application/json

{
    "email": "jme@mail.com",
    "password": "123456"

}

###

DELETE http://localhost:9000/questions/1

### ANSWERS ROUTE

GET http://localhost:9000/questions/1/answers

###

POST http://localhost:9000/questions/1/answers
Content-Type: application/json

{
    "user_id" : 2,
    "answer_text" : "Parce que Mbappe a raté"
}

###

PUT http://localhost:9000/questions/5/answers
Content-Type: application/json

{
    "user_id" : 2,
    "answer_text" : "Marjorie"
}

###

DELETE http://localhost:9000/questions/16/answers
